version: '3.8'

services:
  web:
    build: .
    container_name: biblioteca_app
    ports:
      - "8000:8000"
    volumes:
      # Monta el código local dentro del contenedor.
      # ¡Cualquier cambio que hagan tus devs en el código se reflejará al instante sin reiniciar Docker!
      - .:/app
    environment:
      - PORT=8000